import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import * as engine from '../dist/engine/index.js';
import {samples} from '../dist/samples.js';
import {zhRules} from '../dist/rule-labels.js';
const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8');
const code=(await readFile(new URL('../dist/app.js',import.meta.url),'utf8')).replace(/^import .+;\n/gm,'').replace("const module=await import('./rule-labels.js');zhRules=module.zhRules;","zhRules=window.__labels;");
async function setup(){const dom=new JSDOM(html,{url:'http://localhost',runScripts:'outside-only'});const {window}=dom;Object.assign(window,{TextEncoder,samples,__labels:zhRules,...engine});window.URL.createObjectURL=blob=>{window.__lastBlob=blob;return 'blob:test';};window.URL.revokeObjectURL=()=>{};window.HTMLAnchorElement.prototype.click=function(){window.__downloadName=this.download;};await window.eval(`(async()=>{${code}\n})()`);const q=s=>window.document.querySelector(s);const input=(s,value)=>{q(s).value=value;q(s).dispatchEvent(new window.Event('input',{bubbles:true}));};return {dom,window,q,input,click:s=>q(s).click()};}
test('Chinese synthetic example computes real findings and evidence',async()=>{const {dom,q}=await setup();assert.equal(q('#issue-count').textContent,'3');assert.match(q('#sample-tag').textContent,/合成/);assert.match(q('#evidence-panel').textContent,/20名志愿者/);assert.match(q('footer').textContent,/语义忠实度尚未评估/);dom.window.close();});
test('English toggle translates UI and loads independent English synthetic content',async()=>{const {dom,q,click}=await setup();click('#language');assert.equal(dom.window.document.documentElement.lang,'en');assert.match(q('#source').value,/small pilot/);assert.equal(q('#issue-count').textContent,'3');assert.match(q('#evidence-panel').textContent,/volunteers/);dom.window.close();});
test('Edited input gates stale report export and rerun uses changed input',async()=>{const {dom,q,input,click}=await setup();input('#draft-title','完成率从40%提高到60%');assert.equal(q('#export-json').disabled,true);click('#run-review');assert.equal(q('#issue-count').textContent,'2');assert.equal(q('#export-json').disabled,false);dom.window.close();});
test('Review decision requires a reason, can be filtered and reopened',async()=>{const {dom,q,input,click}=await setup();click('[data-decision="reviewed"]');assert.match(q('#notice').textContent,/至少 3/);input('#review-reason','已核对原文，将补充限定说明。');click('[data-decision="reviewed"]');assert.match(q('#progress-label').textContent,/1 \/ 3/);click('[data-filter="reviewed"]');assert.equal(dom.window.document.querySelectorAll('.finding').length,1);click('#reopen');assert.match(q('#progress-label').textContent,/0 \/ 3/);dom.window.close();});
test('Invalid transcript enters explicit error state',async()=>{const {dom,q,input,click}=await setup();input('#source','definitely not a subtitle file');click('#run-review');assert.match(q('#notice').textContent,/无法完成检查/);assert.match(q('#summary-label').textContent,/无有效报告/);assert.equal(q('#export-json').disabled,true);dom.window.close();});
test('Invalid range is rejected before review',async()=>{const {dom,q,input,click}=await setup();input('[data-range="0"][data-edge="end"]','1');click('#run-review');assert.match(q('#notice').textContent,/时间范围无效/);dom.window.close();});
test('Partial-cue labels do not claim whole quote survived',async()=>{const {dom,q,input,click}=await setup();input('[data-range="0"][data-edge="start"]','9');click('#run-review');assert.match(q('#findings-list').textContent,/剪辑边界/);const target=[...dom.window.document.querySelectorAll('.finding')].find(e=>e.textContent.includes('剪辑边界'));target.click();assert.match(q('#evidence-panel').textContent,/部分重叠 · 词语不确定/);dom.window.close();});
test('No signals keeps semantic fidelity explicitly unassessed',async()=>{const {dom,q,input,click}=await setup();input('[data-range="0"][data-edge="start"]','0');input('[data-range="0"][data-edge="end"]','28');input('#draft-title','');input('#draft-copy','');click('#run-review');assert.equal(q('#issue-count').textContent,'0');assert.match(q('#evidence-panel').textContent,/语义忠实度尚未评估/);assert.match(q('#findings-list').textContent,/这不是通过结论/);dom.window.close();});
test('Untrusted title is rendered as text and not executed',async()=>{const {dom,q,input,click}=await setup();input('#draft-title','<img src=x onerror="window.pwned=true">80%');click('#run-review');assert.equal(q('#evidence-panel img'),null);assert.match(q('.draft-excerpt').textContent,/<img/);assert.equal(dom.window.pwned,undefined);dom.window.close();});
test('Save is explicit download and can preserve stale drafts',async()=>{const {dom,q,input,click,window}=await setup();input('#draft-title','Unfinished draft');click('#save-project');assert.equal(window.__downloadName,'cliplint-project.json');assert.equal(window.localStorage.length,0);assert.equal(window.sessionStorage.length,0);dom.window.close();});
test('All local static references exist and scripts contain no network/storage calls',async()=>{for(const f of ['app.js','styles.css','samples.js','rule-labels.js','favicon.svg','engine/index.js'])assert.ok((await readFile(new URL('../dist/'+f,import.meta.url))).length);assert.doesNotMatch(code,/\b(?:fetch|XMLHttpRequest|WebSocket|sendBeacon)\s*\(/);assert.doesNotMatch(code,/\b(?:localStorage|sessionStorage|indexedDB)\b/);});

async function blobText(window){return new Promise((resolve,reject)=>{const reader=new window.FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsText(window.__lastBlob);});}
async function openProject(window,q,data,size){const f={size:size??JSON.stringify(data).length,text:async()=>JSON.stringify(data)};Object.defineProperty(q('#project-file'),'files',{configurable:true,value:[f]});q('#project-file').dispatchEvent(new window.Event('change'));await new Promise(r=>setTimeout(r,0));}
test('Project round-trip recomputes and retains signature-bound decisions',async()=>{const a=await setup();a.input('#review-reason','Verified the omitted pilot limitation.');a.click('[data-decision="reviewed"]');a.click('#save-project');const p=JSON.parse(await blobText(a.window));assert.equal(p.schema,'cliplint-project');assert.equal(p.decisions['issue-1'].status,'reviewed');const b=await setup();await openProject(b.window,b.q,p);assert.match(b.q('#progress-label').textContent,/1 \/ 3/);assert.match(b.q('#notice').textContent,/项目已导入/);a.dom.window.close();b.dom.window.close();});
test('Imported decisions with changed evidence signature are discarded',async()=>{const a=await setup();a.input('#review-reason','A reason long enough.');a.click('[data-decision="reviewed"]');a.click('#save-project');const p=JSON.parse(await blobText(a.window));p.decisions['issue-1'].signature='mismatched evidence';await openProject(a.window,a.q,p);assert.match(a.q('#progress-label').textContent,/0 \/ 3/);a.dom.window.close();});
test('Malformed project import is rejected without replacing existing inputs',async()=>{const a=await setup();const before=a.q('#source').value;await openProject(a.window,a.q,{schema:'some-other-format'});assert.match(a.q('#notice').textContent,/不是有效/);assert.equal(a.q('#source').value,before);a.dom.window.close();});
test('Markdown export contains source, findings and human decisions',async()=>{const a=await setup();a.input('#review-reason','Checked all nearby source cues.');a.click('[data-decision="dismissed"]');a.click('#export-md');const md=await blobText(a.window);assert.equal(a.window.__downloadName,'cliplint-review.md');assert.match(md,/Checked all nearby source cues/);assert.match(md,/Semantic fidelity remains unassessed/);assert.match(md,/20名志愿者/);a.dom.window.close();});
test('Draft save and import preserves invalid raw ranges without pretending review succeeded',async()=>{const a=await setup();a.input('[data-range="0"][data-edge="end"]','unfinished');a.click('#save-project');const p=JSON.parse(await blobText(a.window));assert.equal(p.report,null);await openProject(a.window,a.q,p);assert.equal(a.q('[data-range="0"][data-edge="end"]').value,'unfinished');assert.equal(a.q('#export-json').disabled,true);assert.match(a.q('#notice').textContent,/时间范围无效/);a.dom.window.close();});

test('Stale evidence cannot receive keyboard/programmatic review decisions',async()=>{const a=await setup();a.input('#review-reason','Ready to record this finding.');a.input('#draft-title','Changed draft 80%');a.click('[data-decision="reviewed"]');assert.match(a.q('#progress-label').textContent,/0 \/ 3/);assert.match(a.q('#notice').textContent,/输入已更改/);assert.equal(a.q('.review-panel').inert,true);a.dom.window.close();});

test('Project saves omit a potentially huge recomputable report',async()=>{const a=await setup();a.click('#save-project');const p=JSON.parse(await blobText(a.window));assert.equal(p.report,null);assert.ok(p.inputs.source);assert.ok(p.rawRanges);a.dom.window.close();});
test('Overlong range drafts cannot create an unimportable project',async()=>{const a=await setup();a.input('[data-range="0"][data-edge="end"]','x'.repeat(31));a.click('#save-project');assert.match(a.q('#notice').textContent,/30 个字符/);assert.equal(a.window.__downloadName,undefined);a.dom.window.close();});
test('Markdown keeps source and reasons verbatim inside sufficiently long fences',async()=>{const a=await setup();const payload='<img src="https://example.org/tracking">literal **evidence**\n```\n# Pretend heading';a.input('#review-reason',payload);a.click('[data-decision="reviewed"]');a.click('#export-md');const md=await blobText(a.window);assert.ok(md.includes('````text\n'+payload+'\n````'));assert.match(md,/## Original source \/ 原始稿件\n\n```text/);a.dom.window.close();});
test('Changed checked inputs invalidate imported decisions',async()=>{const a=await setup();a.input('#review-reason','Checked the old publishing copy.');a.click('[data-decision="reviewed"]');a.click('#save-project');const p=JSON.parse(await blobText(a.window));p.inputs.copy='A new and substantively different claim.';await openProject(a.window,a.q,p);assert.match(a.q('#progress-label').textContent,/0 \/ 3/);a.dom.window.close();});
test('Source stays labelled synthetic after copy/range edits',async()=>{const a=await setup();a.input('#draft-title','An edited title');a.input('[data-range="0"][data-edge="end"]','20');assert.match(a.q('#sample-tag').textContent,/合成示例/);a.click('#run-review');a.click('#language');assert.equal(a.q('#draft-title').value,'An edited title');assert.match(a.q('#sample-tag').textContent,/Synthetic example/);a.dom.window.close();});
test('Filter and finding navigation restore keyboard focus',async()=>{const a=await setup();a.click('[data-filter="open"]');assert.equal(a.window.document.activeElement.dataset.filter,'open');a.click('.finding');assert.equal(a.window.document.activeElement.dataset.issue,'issue-1');a.dom.window.close();});
test('Project import gives a specific size-limit error',async()=>{const a=await setup();await openProject(a.window,a.q,{},9*1024*1024);assert.match(a.q('#notice').textContent,/8 MB/);a.dom.window.close();});
test('Browser engine modules are byte-identical to the original source snapshot',async()=>{const {readdir}=await import('node:fs/promises');for(const file of await readdir(new URL('../engine/src/',import.meta.url))){if(file.endsWith('.js'))assert.equal(await readFile(new URL('../engine/src/'+file,import.meta.url),'utf8'),await readFile(new URL('../dist/engine/'+file,import.meta.url),'utf8'),file);}});
test('Explicit source speaker metadata remains visible in evidence',async()=>{const a=await setup();const parsed=engine.parseTranscript(samples.zh.source);a.input('#source',JSON.stringify(parsed.cues.map(c=>({...c,speaker:'明确标注的嘉宾'}))));a.input('#format','json');a.click('#run-review');assert.match(a.q('.cue-speaker').textContent,/明确标注的嘉宾/);a.dom.window.close();});
